---
- name: Install git
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Check current state of ~/.gitconfig
  ansible.builtin.stat:
    path: "{{ home_dir }}/.gitconfig"
  register: gitconfig_stat

- name: Back up existing ~/.gitconfig
  ansible.builtin.command:
    cmd: >
      mv {{ home_dir }}/.gitconfig
      {{ home_dir }}/.gitconfig.bak.{{ ansible_facts['date_time']['iso8601_basic_short'] }}
  when:
    - gitconfig_stat.stat.exists
    - not gitconfig_stat.stat.islnk

- name: Symlink gitconfig into place
  ansible.builtin.file:
    src: "{{ role_path }}/files/gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
    state: link
    force: false
