---
- name: Remove gitconfig symlink
  ansible.builtin.file:
    path: "{{ home_dir }}/.gitconfig"
    state: absent

- name: Remove git package
  ansible.builtin.package:
    name: git
    state: absent
  become: true
